# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0einternal.proto\"-\n\x07Product\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x02(\x03\"K\n\x07Request\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\t\n\x01x\x18\x02 \x02(\x03\x12\t\n\x01y\x18\x03 \x02(\x03\x12\x19\n\x07product\x18\x04 \x03(\x0b\x32\x08.Product')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=18
  _PRODUCT._serialized_end=63
  _REQUEST._serialized_start=65
  _REQUEST._serialized_end=140
# @@protoc_insertion_point(module_scope)
