# Generated by Django 4.2 on 2023-04-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_x', models.IntegerField()),
                ('destination_y', models.IntegerField()),
                ('user_id', models.IntegerField(null=True)),
                ('status', models.TextField(default='purchase')),
                ('truck_id', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(default='purchase')),
                ('status', models.TextField(default='open')),
                ('pk_id', models.ForeignKey(db_column='pk_id', on_delete=django.db.models.deletion.CASCADE, to='amazon.package')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.package')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.warehouse')),
            ],
        ),
    ]
